{
    "message_id": "10000",
    "message": null,
    "result": true,
    "object": [
        {
            "id": null,
            "productId": 27637,
            "eventCode": "202403_0325_1",
            "userEmail": "yi.shen",
            "linkTime": null,
            "linkTypeId": null,
            "eventGroupId": 1317,
            "startDate": "2024-03-29",
            "endDate": "2024-03-29",
            "recUpdateUser": "yi.shen",
            "recCreateTime": null,
            "recUpdateTime": null,
            "productUrl": "https://www.sayweee.com/en/product/view/27637",
            "imageUrl": "https://img06.weeecdn.com/item/image/761/495/1C67E7B4C9F4DE85.jpg",
            "ethnicity": "indian",
            "productTitle": "Kurkure Chilli Chatka",
            "productCatalogueNum": "0501",
            "productCatalogue": "Chips",
            "eventGroupTitle": "0325",
            "groupId": 1,
            "promotionEventProductSalesOrgResponseDtos": [
                {
                    "id": 8738660,
                    "ppsPromotionProductId": null,
                    "productId": 27637,
                    "salesOrgId": 7,
                    "defaultSalesOrgId": 7,
                    "linkToPriceSpecial": null,
                    "discountPercentage": 20,
                    "promotionPrice": 1.19,
                    "basePrice": 1.49,
                    "pricePriority": "N",
                    "maxQuantity": 4,
                    "businessReason": "Vendor Sponsored Cost Reduction",
                    "forecastBaseQty": null,
                    "forecastUpliftQty": null,
                    "isApproved": null,
                    "approverUser": null,
                    "recApproveTime": null,
                    "recUpdateUser": "yi.shen",
                    "tag": "featured",
                    "isLightningDeal": null,
                    "ownerId": 9664244,
                    "ownerName": "yogesh.lal",
                    "avgPrice": 0.54,
                    "memberPrice": 1.19,
                    "memberDiscountPercentage": 20
                },
                {
                    "id": 8738661,
                    "ppsPromotionProductId": null,
                    "productId": 27637,
                    "salesOrgId": 23,
                    "defaultSalesOrgId": 23,
                    "linkToPriceSpecial": null,
                    "discountPercentage": 15,
                    "promotionPrice": 1.09,
                    "basePrice": 1.29,
                    "pricePriority": "N",
                    "maxQuantity": 4,
                    "businessReason": "Vendor Sponsored Cost Reduction",
                    "forecastBaseQty": null,
                    "forecastUpliftQty": null,
                    "isApproved": null,
                    "approverUser": null,
                    "recApproveTime": null,
                    "recUpdateUser": "yi.shen",
                    "tag": "featured",
                    "isLightningDeal": null,
                    "ownerId": 7244906,
                    "ownerName": null,
                    "avgPrice": null,
                    "memberPrice": 0.99,
                    "memberDiscountPercentage": 20
                },
                {
                    "id": 8738659,
                    "ppsPromotionProductId": null,
                    "productId": 27637,
                    "salesOrgId": 29,
                    "defaultSalesOrgId": 29,
                    "linkToPriceSpecial": null,
                    "discountPercentage": 15,
                    "promotionPrice": 1.09,
                    "basePrice": 1.29,
                    "pricePriority": "N",
                    "maxQuantity": 2,
                    "businessReason": "Vendor Sponsored Cost Reduction",
                    "forecastBaseQty": null,
                    "forecastUpliftQty": null,
                    "isApproved": null,
                    "approverUser": null,
                    "recApproveTime": null,
                    "recUpdateUser": "yi.shen",
                    "tag": "featured",
                    "isLightningDeal": null,
                    "ownerId": 9679508,
                    "ownerName": null,
                    "avgPrice": null,
                    "memberPrice": 0.99,
                    "memberDiscountPercentage": 20
                }
            ],
            "salesOrgIds": [
                7,
                23,
                29
            ],
            "productPromoStartTime": "2024-03-29 00:00:00",
            "productPromoEndTime": "2024-03-29 22:56:57"
        }
    ]
}